Returncode

diff --git a/createCoupon b/createCoupon
--- a/createCoupon
+++ b/createCoupon
@@ -27,5 +27,11 @@ else
         echo "✅ ${GREEN} coupon name not already used!${RESET}"
         echo "🧙‍♂️ creating the coupon code, check log from wp"
         wp wc shop_coupon create --code=${COUPON_NAME} --amount='10' --discount_type='percent' --individual_use=true --excluded_product_ids="[19341]" --usage_limit_per_user='1' --description='Influencer-Code' --user=${WP_USERNAME}
+                    if [ $? -eq 0 ]; then
+                echo "✅ ${GREEN}Coupon ${COUPON_NAME} created successfully!${RESET}"
+            else 
+                echo "❌ ${RED}Coupon creation failed!${RESET}" >&2
+                exit 1
+            fi
     fi
 fi
